### ISSUE TITLE
Create videos database for simulation component

### ISSUE THREAD

**Issue by cristi161** [andreeapupe/ProiectPCD#4]
Download [this video](https://www.youtube.com/watch?v=oyfrPrGmBL4&ab_channel=TorontoRoadcamsRawDashCamFootage) and  slice it to 8 min chunks and 2 min chunks. 10 videos of both periods. 
Name them using convention: min8_1.mp4 and min2_1.mp4

Also if you find another video, fell free to use it.

**Comment by andreeapupe** [comment]
[Drive](https://drive.google.com/drive/u/2/folders/0AI7pXut-mSllUk9PVA)

**Comment by andreeapupe** [comment]
[Google Drive - Sliced videos](https://drive.google.com/drive/u/2/folders/0AI7pXut-mSllUk9PVA)
